const saved=JSON.parse(localStorage.getItem("quantix-settings")||"{}");let API_URL=saved.api||window.QUANTIX_API_URL||"";let timer=null;
const $=s=>document.querySelector(s);function setOnline(v){$("#apiPill").classList.toggle("online",v);$("#apiPill").innerHTML='<i></i> '+(v?"ONLINE":"OFFLINE");$("#sideStatus").textContent=v?"LIVE":"OFFLINE";$("#sideStatus").style.color=v?"var(--good)":"var(--warn)";$(".dot").style.background=v?"var(--good)":"var(--bad")}
function fmt(n,p=2){return typeof n==="number"&&isFinite(n)?n.toFixed(p):"—"}
async function get(path){if(!API_URL)return null;const r=await fetch(API_URL.replace(/\/$/,"")+path,{cache:"no-store"});if(!r.ok)throw Error(r.status);return r.json()}
function renderTrending(d){$("#trendList").innerHTML=(d?.results||[]).slice(0,8).map(x=>'<div class="row"><b>'+x.ticker+'</b><div><span>'+fmt(x.price)+'</span><small>'+fmt(x.change_5m*100)+'% · '+new Date(x.timestamp).toLocaleTimeString()+'</small></div><b class="'+(x.change_5m>=0?"good":"bad")+'">'+(x.change_5m>=0?"UP":"DOWN")+'</b></div>').join("")||'<p>Waiting for enough live bars.</p>'}
let scannerRows=[];function renderScanner(){const q=$("#search").value.toUpperCase(),f=$("#filter").value;$("#scannerBody").innerHTML=scannerRows.filter(x=>(!q||x.ticker.includes(q))&&(f==="all"||x.signal===f)).slice(0,250).map(x=>'<tr><td><b>'+x.ticker+'</b></td><td>'+fmt(x.price)+'</td><td>'+fmt(x.probability_up*100,1)+'%</td><td class="'+(x.signal==="positive"?"good":x.signal==="negative"?"bad":"warn")+'">'+x.signal.toUpperCase()+'</td><td>'+fmt(x.rsi,1)+'</td><td class="'+(x.momentum_10>=0?"good":"bad")+'">'+fmt(x.momentum_10*100,2)+'%</td><td>'+fmt(x.volatility*100,2)+'%</td></tr>').join("")||'<tr><td colspan="7">Waiting for model-ready live data.</td></tr>'}
async function refresh(){try{const [status,model,trend,scan,sum]=await Promise.all([get("/v1/status"),get("/v1/model"),get("/v1/trending"),get("/v1/scanner"),get("/v1/summary")]);setOnline(true);renderTrending(trend);scannerRows=scan?.results||[];renderScanner();$("#headline").textContent=sum?.headline||"Live market state";$("#summary").textContent=(sum?.points||[]).join(" ");$("#tracked").textContent=scan?.count?scan.count+" live":"1,000+";$("#universe").textContent="1,000+";$("#aiSummary").textContent=(sum?.points||[]).join(" ")||"Live research summary unavailable.";if(model?.status==="ready"){$("#modelStatus").textContent="READY";$("#modelStatus").classList.add("ready");$("#progress").style.width="100%";$("#algorithm").textContent=model.model_type;$("#features").textContent=(model.features||[]).length+" features";$("#trained").textContent=model.trained_at?new Date(model.trained_at).toLocaleString():"—";$("#modelVersion").textContent=model.model_version||"—";$("#horizon").textContent=(model.horizon_days||"—")+"D";$("#auc").textContent=fmt(model.metrics?.roc_auc,3)}else{$("#modelStatus").textContent="NOT TRAINED";$("#progress").style.width="0%"}const latest=Object.values(status?.latest||{});if(latest.length){const age=Math.max(0,Date.now()-new Date(latest[0].timestamp).getTime());$("#latency").textContent=age+" ms since provider tick";$("#diagnostics").innerHTML='<div><span>Provider</span><b>Twelve Data</b></div><div><span>Stream</span><b class="good">CONNECTED</b></div><div><span>Universe</span><b>1,000+</b></div><div><span>Updates</span><b>Automatic</b></div>')}}catch(e){setOnline(false)}}
function schedule(){clearInterval(timer);timer=setInterval(refresh,Number($("#interval").value||1000))}
$("#refresh").onclick=refresh;$("#search").oninput=renderScanner;$("#filter").onchange=renderScanner;$("#interval").onchange=schedule;
$("#theme").onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem("quantix-theme",t);$("#themeSelect").value=t};$("#themeSelect").onchange=e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem("quantix-theme",e.target.value)};
$("#apiField").value=API_URL;$("#saveSettings").onclick=()=>{API_URL=$("#apiField").value.trim().replace(/\/$/,"");localStorage.setItem("quantix-settings",JSON.stringify({api:API_URL}));refresh()};document.documentElement.dataset.theme=localStorage.getItem("quantix-theme")||"dark";$("#themeSelect").value=document.documentElement.dataset.theme;schedule();refresh();