const saved=JSON.parse(localStorage.getItem("quantix")||"{}");let API=saved.api||window.QUANTIX_API_URL||"";let interval=Number(saved.interval||1000),timer;
const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function connection(live){$("#statusPill").classList.toggle("live",live);$("#statusPill").textContent=live?"LIVE":"OFFLINE";$("#connection").textContent=live?"Live":"Offline";$("#statusDot").style.background=live?"var(--good)":"var(--bad)"}
async function get(p){if(!API)return null;const r=await fetch(API.replace(/\/$/,"")+p,{cache:"no-store"});if(!r.ok)throw Error(r.status);return r.json()}
function renderTrend(d){$("#trending").innerHTML=(d?.results||[]).slice(0,10).map(x=>'<div class="trend"><b>'+esc(x.ticker)+'</b><div><span>'+Number(x.price).toFixed(2)+'</span><small>'+((x.change_5m||0)*100).toFixed(2)+'% · '+esc(x.provider)+'</small></div><b class="'+(x.change_5m>=0?"good":"bad")+'">'+(x.change_5m>=0?"UP":"DOWN")+'</b></div>').join("")||'<div class="empty">No live bars yet.</div>'}
let rows=[];
function renderScanner(){const q=$("#search").value.toUpperCase(),f=$("#signal").value;$("#scannerBody").innerHTML=rows.filter(x=>(!q||x.ticker.includes(q))&&(f==="all"||x.signal===f)).slice(0,300).map(x=>'<tr><td>'+esc(x.ticker)+'</td><td>'+Number(x.price).toFixed(2)+'</td><td>'+Number(x.probability_up*100).toFixed(1)+'%</td><td class="'+(x.signal==="positive"?"good":x.signal==="negative"?"bad":"")+"">'+esc(x.signal)+'</td><td>'+Number(x.rsi).toFixed(1)+'</td><td>'+Number(x.momentum_10*100).toFixed(2)+'%</td><td>'+Number(x.volatility*100).toFixed(2)+'%</td></tr>').join("")||'<tr><td colspan="7" class="empty">No model-ready instruments.</td></tr>'}
function renderWatch(d){const arr=Object.values(d?.latest||{}).slice(0,24);$("#watchlistGrid").innerHTML=arr.map(x=>'<div class="watch"><b>'+esc(x.symbol)+'</b><small>'+Number(x.price).toFixed(2)+' · '+esc(x.provider)+'</small></div>').join("")||'<div class="empty">Waiting for provider.</div>'}
async function refresh(){try{const [s,m,t,c,sum]=await Promise.all([get("/v1/status"),get("/v1/model"),get("/v1/trending"),get("/v1/scanner"),get("/v1/summary")]);connection(!!s);renderTrend(t);renderWatch(s);rows=c?.results||[];renderScanner();$("#liveCount").textContent=s?.live_symbols??"—";$("#universeCount").textContent="universe "+(s?.universe_size??"—");$("#marketState").textContent=rows.length? "ACTIVE":"WAITING";$("#marketSub").textContent=sum?.headline||"Awaiting feed";$("#summary").textContent=(sum?.points||[]).join(" ")||"No live snapshot yet.";$("#chips").innerHTML=["Momentum","Trend","Volume","Volatility"].map(x=>'<span>'+x+'</span>').join("");if(m?.status==="ready"){$("#modelStatus").textContent="Ready";$("#algorithm").textContent=m.model_type||"—";$("#features").textContent=(m.features||[]).length+" features";$("#horizon").textContent=(m.horizon_days||"—")+"D";$("#trained").textContent=m.trained_at?new Date(m.trained_at).toLocaleDateString():"—";$("#modelVer").textContent=m.model_version||"—";$("#auc").textContent=m.metrics?.roc_auc!=null?Number(m.metrics.roc_auc).toFixed(3):"—"}$("#providers").innerHTML=Object.entries(s?.providers||{}).map(([k,v])=>'<div class="provider"><span>'+esc(k)+'</span><b class="'+(v?"good":"")+'">'+(v?"CONFIGURED":"NOT CONFIGURED")+'</b></div>').join("");const latest=Object.values(s?.latest||{});if(latest.length){const age=Math.max(0,Date.now()-latest[0].timestamp_ms);$("#latency").textContent=age+" ms"}}catch(e){connection(false)}}
function schedule(){clearInterval(timer);timer=setInterval(refresh,interval)}
$("#themeBtn").onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=t;localStorage.setItem("quantix-theme",t)}
$("#search").oninput=renderScanner;$("#signal").onchange=renderScanner;$("#refreshRate").onchange=e=>{interval=Number(e.target.value);localStorage.setItem("quantix",JSON.stringify({api:API,interval}));schedule()};$("#save").onclick=()=>{API=$("#api").value.trim();localStorage.setItem("quantix",JSON.stringify({api:API,interval}));refresh()};$("#api").value=API;$("#refreshRate").value=String(interval);document.documentElement.dataset.theme=localStorage.getItem("quantix-theme")||"dark";schedule();refresh();